### ISSUE TITLE
Unterstützung für DEEBOT T30 PRO OMNI

### ISSUE THREAD

**Issue by niclas911** [DeebotUniverse/client.py#640] opened 2024-12-07 11:35 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Könnten Sie bitte DEEBOT T30 PRO OMNI hinzufügen?

Nach dem Update 2024.12 funktionierte es nicht mehr. Vielen Dank

### On which deebot device (vacuum) you have the issue?

DEEBOT T30 PRO OMNI

### Which version of the deebot-client are you using?

letzte

### Country

De

### Continent

eu

**Comment by edenhaus** [comment] 2024-12-07 18:29
Closing it as the issue is not written in English and it's missing information like model class and co

**Closed by edenhaus** 2024-12-07 18:29 UTC
Labels: bug
