### ISSUE TITLE
 Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}

### ISSUE THREAD

**Issue by StefanoGiu** [DeebotUniverse/client.py#301] opened 2023-09-20 12:46 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Map is blurry, not well defined. I have Ecovacs Deebot Omni X1

 Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}

### On which deebot vacuum you have the issue?

Deebot X1 Omni

### Which version of the deebot-client are you using?

3.0.0

### Country

it

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

### Additional information

 Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}

**Comment by edenhaus** [comment] 2023-09-20 15:08
Duplicate of https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/268

**Closed by edenhaus** 2023-09-20 15:08 UTC
Labels: bug

**Comment by StefanoGiu** [comment] 2023-09-20 15:25
Why not planned??? Why Closed??? You just ignore bugs???

**Comment by edenhaus** [comment] 2023-09-20 16:14
I keep one issue per bug/feature request, which is a duplicate of the above-mentioned one.
You have already reported the issue there. There is no need to open it here again.
